# Generated by Django 4.2.4 on 2023-08-18 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogPosts', '0002_alter_comments_user_alter_like_post_alter_like_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='comments',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='reported_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
