# Generated by Django 4.2.4 on 2023-08-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPosts', '0004_remove_like_comment_remove_like_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to='BlogPosts.userprofile'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='reported_comments', to='BlogPosts.userprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='BlogPosts.userprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='reported_posts', to='BlogPosts.userprofile'),
        ),
    ]
