# Generated by Django 4.2.4 on 2023-08-21 14:54

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPosts', '0006_alter_comments_liked_by_alter_comments_reported_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_content',
            field=froala_editor.fields.FroalaField(default='dsddf'),
            preserve_default=False,
        ),
    ]
