# Generated by Django 4.2.4 on 2023-08-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPosts', '0007_remove_post_post_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='approved',
        ),
    ]
