# Generated by Django 4.2.4 on 2023-08-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPosts', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
