# Generated by Django 4.2.4 on 2023-08-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPosts', '0013_alter_comments_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
