# Generated by Django 4.2.4 on 2023-08-22 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPosts', '0014_alter_comments_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogPosts.comments'),
        ),
    ]
