# Generated by Django 4.2.4 on 2023-08-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPosts', '0017_remove_suggestion_reply_suggestionreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='content',
            new_name='text',
        ),
    ]
