# Generated by Django 4.2.4 on 2023-08-28 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPosts', '0024_alter_post_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_change_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
