# Generated by Django 4.2.4 on 2023-08-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPosts', '0025_userprofile_email_change_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_change_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
