# Generated by Django 4.2.4 on 2023-08-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPosts', '0026_userprofile_new_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_change_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='new_email',
        ),
    ]
